apiVersion: v1
kind: Pod
metadata:
  name: test-storage-0
  namespace: zoe-test
spec:
  containers:
    - image: ubuntu
      imagePullPolicy: IfNotPresent
      name: myvolumes-container
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from Bash!; dd if=/dev/zero of=bigFile1.txt bs=1M count=1024; echo create end; du -sh bigFile1.txt; sleep 5000000s"]
      resources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "1Gi"